import { describe, it, expect } from "vitest";
import { parseDNAFile } from "./dna";

/**
 * The most consequential thing this app does. A genotype parsed wrong
 * misreports someone's DNA back to them, and nothing downstream would catch it.
 */
describe("parseDNAFile", () => {
  describe("23andMe", () => {
    const file = [
      "# This data file generated by 23andMe",
      "# rsid\tchromosome\tposition\tgenotype",
      "rs4988235\t2\t136608646\tAA",
      "rs1801133\t1\t11856378\tCT",
      "rs53576\t3\t8804371\tGG",
    ].join("\n");

    it("is detected by default", () => {
      expect(parseDNAFile(file).format).toBe("23andMe");
    });

    it("reads genotype, chromosome and position", () => {
      const { variants, totalCount } = parseDNAFile(file);
      expect(totalCount).toBe(3);
      expect(variants.get("rs4988235")).toEqual({
        genotype: "AA", chromosome: "2", position: "136608646",
      });
      expect(variants.get("rs1801133").genotype).toBe("CT");
    });

    it("ignores comments and the header row", () => {
      expect(parseDNAFile(file).variants.has("rsid")).toBe(false);
    });
  });

  describe("AncestryDNA", () => {
    const file = [
      "#AncestryDNA raw data download",
      "rsid\tchromosome\tposition\tallele1\tallele2",
      "rs4988235\t2\t136608646\tA\tG",
      "rs1801133\t1\t11856378\tC\tC",
    ].join("\n");

    it("is detected from its allele1/allele2 header", () => {
      expect(parseDNAFile(file).format).toBe("AncestryDNA");
    });

    it("joins the two allele columns into one genotype", () => {
      const { variants } = parseDNAFile(file);
      expect(variants.get("rs4988235").genotype).toBe("AG");
      expect(variants.get("rs1801133").genotype).toBe("CC");
    });

    it("strips the zero used for a no-call", () => {
      const withNoCall = [
        "rsid\tchromosome\tposition\tallele1\tallele2",
        "rs111\t1\t100\tA\t0",
      ].join("\n");
      expect(parseDNAFile(withNoCall).variants.get("rs111").genotype).toBe("A");
    });
  });

  describe("VCF", () => {
    const file = [
      "##fileformat=VCFv4.2",
      "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE",
      "1\t100\trs123\tA\tG\t.\t.\t.\tGT\t0/1",
      "2\t200\trs456\tC\tT\t.\t.\t.\tGT\t1/1",
      "3\t300\trs789\tG\tA\t.\t.\t.\tGT\t0|0",
    ].join("\n");

    it("is detected from the fileformat header", () => {
      expect(parseDNAFile(file).format).toBe("VCF");
    });

    it("resolves a heterozygous call to reference plus alternate", () => {
      expect(parseDNAFile(file).variants.get("rs123").genotype).toBe("AG");
    });

    it("resolves a homozygous alternate call", () => {
      expect(parseDNAFile(file).variants.get("rs456").genotype).toBe("TT");
    });

    it("resolves a phased homozygous reference call", () => {
      expect(parseDNAFile(file).variants.get("rs789").genotype).toBe("GG");
    });

    it("skips rows with no rsID", () => {
      const noId = [
        "##fileformat=VCFv4.2",
        "1\t100\t.\tA\tG\t.\t.\t.\tGT\t0/1",
      ].join("\n");
      expect(parseDNAFile(noId).totalCount).toBe(0);
    });
  });

  describe("robustness", () => {
    it("handles an empty file without throwing", () => {
      expect(parseDNAFile("").totalCount).toBe(0);
    });

    it("handles Windows line endings", () => {
      const crlf = "rs4988235\t2\t136608646\tAA\r\nrs1801133\t1\t11856378\tCT\r\n";
      expect(parseDNAFile(crlf).totalCount).toBe(2);
      expect(parseDNAFile(crlf).variants.get("rs4988235").genotype).toBe("AA");
    });

    it("skips malformed rows rather than abandoning the file", () => {
      const messy = [
        "rs4988235\t2\t136608646\tAA",
        "garbage line with no tabs",
        "rs1801133\t1\t11856378\tCT",
      ].join("\n");
      expect(parseDNAFile(messy).totalCount).toBe(2);
    });

    it("keeps the last entry when an rsID repeats", () => {
      const dupes = ["rs1\t1\t1\tAA", "rs1\t1\t1\tGG"].join("\n");
      expect(parseDNAFile(dupes).variants.get("rs1").genotype).toBe("GG");
    });
  });
});
